# ====================
# Run Configuration
# ====================
run: 
  name: TransformerSeq2Seq_2
  runs_dir: ./runs/seq2seq

# ====================
# Training Parameters
# ====================
train:
  steps: 50000
  lr: 0.0001

# ====================
# Model Configuration
# ====================
model:
  d_model: 256
  num_heads: 4
  num_encoder_layers: 4
  num_decoder_layers: 4
  dropout: 0.2

# ====================
# Dataset Configuration
# ====================
data:
  dataset: ted_talks
  source_key: en
  target_key: fr

  vocab_size: 10000
  vocab_path: runs/seq2seq/TransformerSeq2Seq/training/vocab.json
  batch_size: 64
  block_size: 192

# ====================
# Sampling Parameters
# ====================
sampling:
  num_samples: 8
  max_tokens: 256

# ====================
# Logging Parameters
# ====================
logging:

  wandb:
    enable: true
    save_ckpt: 0

  loss_interval: 1
  ckpt_interval: 10000
  sample_interval: 5000