run: 
  name: test
  runs_dir: ./runs

train:
  steps: 1
  lr: 0.0001

model:
  d_model: 512
  num_heads: 4
  num_encoder_layers: 2
  num_decoder_layers: 2
  dropout: 0.1

data:
  dataset: ted_talks
  source_key: en
  target_key: fr
  batch_size: 1
  vocab_size: 256
  block_size: 256