# ====================
# Run Configuration
# ====================
run: 
  name: TransformerSeq2Seq_valid
  runs_dir: ./runs/seq2seq

# ====================
# Training Configuration
# ====================
train:
  steps: 50000
  lr: 0.0001

# ====================
# Model Configuration
# ====================
model:
  d_model: 256
  num_heads: 4
  num_encoder_layers: 4
  num_decoder_layers: 4
  dropout: 0.2

# ====================
# Dataset Configuration
# ====================
data:
  dataset: ted_talks
  source_key: en
  target_key: fr
  batch_size: 64
  context_length: 256

# ====================
# Tokenization Configuration
# ====================
tokenizer:
  vocab_size: 10000
  vocab_path: null

# ====================
# Sampling Configuration
# ====================
sampling:
  num_samples: 8
  max_tokens: 256

# ====================
# Logging Configuration
# ====================
logging:

  wandb:
    enable: true
    save_ckpt: 0

  loss_steps: 1
  valid_steps: 1000
  ckpt_steps: 10000
  sample_steps: 5000